/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bharatx.sdk.sample.java;
import org.json.JSONObject;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private static String generateSignature(String payload, String privateKey) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        md.update(payload.getBytes(StandardCharsets.UTF_8));
        md.update(privateKey.getBytes(StandardCharsets.UTF_8));
        
        return Base64.getEncoder().encodeToString(md.digest());
    }

    public static void main(String[] args) {
        JSONObject data = new JSONObject();

        data.put("merchantTransactionId", "txn00");
        data.put("userPhoneNumber", "+919840013290");
        data.put("userId", "user00");
        data.put("amount", 10000);

        String payload = data.toString();
        System.out.println("The payload is:" + payload);

        String privateApiKey = "privateKey";
        try {
        String signature = App.generateSignature(payload, privateApiKey);
        
        System.out.print("Generated signature:");
        System.out.println(signature);
        } catch (Exception a) {
            System.err.println(a.toString());
        }
    }
}
